### ISSUE TITLE
Any way to stop the repeated missing RuboCop gem warning?

### ISSUE THREAD

**Issue by justin808** [sirlantis/rubocop-for-rubymine#12]
This is caused when I switch to projects not using rubocop as my settings for RubyMine for RuboCop are not project specific.

![linters_rake_-_investor-dashboard_-____clients_madrone_investor-dashboard__and_gemfile_-_rebar_-____railsonmaui_rebar_](https://cloud.githubusercontent.com/assets/1118459/7335989/2b10a488-eb7f-11e4-86d7-5dadcf6fe2e2.jpg)

**Comment by justin808** [comment]
BTW, thanks for the awesome plugin!

**Comment by sirlantis** [comment]
This is interesting. https://github.com/sirlantis/rubocop-for-rubymine/blob/5e3670677e0ab8462bb29e404ad120d661e3155c/src/io/github/sirlantis/rubymine/rubocop/RubocopTask.kt#L50-L53 should check, whether the project has a `.rubocop.yml` before running any Ruby code (which will then trigger those warnings).

Do those projects have a `.rubocop.yml`?

**Comment by tannermares** [comment]
![image](https://cloud.githubusercontent.com/assets/1806545/7539729/c044c0a6-f55d-11e4-9d10-d4e96fb73f76.png)
![image](https://cloud.githubusercontent.com/assets/1806545/7539737/cc04c15c-f55d-11e4-8e5d-ac6104ec32e3.png)

I appear to be having the same issue. Though my error is due to bundler looking for `diplomat-0.6.1` which it cannot find.  

I do have a `.rubocop.yml` in this project.

**Comment by tannermares** [comment]
@justin808 what is at the end of your error balloon?

**Comment by justin808** [comment]
Make an error in any rake task (say while editing one, save it as invalid) and the plugin goes berserk.

**Comment by mbasset** [comment]
I also have this same issue. It tends to happen when the Gemfile is updated or ruby version changed or rubocop gem is not installed.

**Comment by levilansing** [comment]
+1 I love the plugin but this error message drives me crazy every time I change my Gemfile, especially if I run into dependency issues because the errors just keep piling up until bundle install succeeds. Is there any way we could get just one error that is much smaller so it doesn't cover half the editor? Ideally it would go away once the problem is solved as well! 

Yesterday I had to click the little x about 30 times :/

**Comment by sirlantis** [comment]
I've changed this now to kill previous messages of the same time. So you should only see one of those messages appear.

**Comment by levilansing** [comment]
wonderful! thanks!
